// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokManager.Web.Data;

#nullable disable

namespace PokManager.Web.Migrations
{
    [DbContext(typeof(PokManagerDbContext))]
    partial class PokManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PokManager.Web.Data.Entities.ConfigurationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationDataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IncludedSettingsJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPartial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapCompatibility")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId")
                        .IsUnique();

                    b.HasIndex("Type", "Category");

                    b.ToTable("ConfigurationTemplates");
                });

            modelBuilder.Entity("PokManager.Web.Data.Entities.InstanceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("CurrentPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPvE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemoryUsageMB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerMap")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uptime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "Timestamp");

                    b.ToTable("InstanceSnapshots");
                });

            modelBuilder.Entity("PokManager.Web.Data.Entities.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstanceSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceSnapshotId");

                    b.HasIndex("InstanceId", "Timestamp");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("PokManager.Web.Data.Entities.PlayerSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstanceSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceSnapshotId");

                    b.HasIndex("InstanceId", "SteamId", "JoinedAt");

                    b.ToTable("PlayerSessions");
                });

            modelBuilder.Entity("PokManager.Web.Data.Entities.TelemetrySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<int>("Fps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameStatsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstanceSnapshotId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MemoryUsageMB")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetworkInKBps")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetworkOutKBps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TickRate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceSnapshotId");

                    b.HasIndex("InstanceId", "Timestamp");

                    b.ToTable("TelemetrySnapshots");
                });

            modelBuilder.Entity("PokManager.Web.Data.Entities.LogEntry", b =>
                {
                    b.HasOne("PokManager.Web.Data.Entities.InstanceSnapshot", "InstanceSnapshot")
                        .WithMany("LogEntries")
                        .HasForeignKey("InstanceSnapshotId");

                    b.Navigation("InstanceSnapshot");
                });

            modelBuilder.Entity("PokManager.Web.Data.Entities.PlayerSession", b =>
                {
                    b.HasOne("PokManager.Web.Data.Entities.InstanceSnapshot", "InstanceSnapshot")
                        .WithMany("PlayerSessions")
                        .HasForeignKey("InstanceSnapshotId");

                    b.Navigation("InstanceSnapshot");
                });

            modelBuilder.Entity("PokManager.Web.Data.Entities.TelemetrySnapshot", b =>
                {
                    b.HasOne("PokManager.Web.Data.Entities.InstanceSnapshot", "InstanceSnapshot")
                        .WithMany("TelemetrySnapshots")
                        .HasForeignKey("InstanceSnapshotId");

                    b.Navigation("InstanceSnapshot");
                });

            modelBuilder.Entity("PokManager.Web.Data.Entities.InstanceSnapshot", b =>
                {
                    b.Navigation("LogEntries");

                    b.Navigation("PlayerSessions");

                    b.Navigation("TelemetrySnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
